### ISSUE TITLE
Can't install flatpaks through yumex on Nobara 40

### ISSUE THREAD

**Issue by M1Labbe** [timlau/yumex-ng#100] opened 2024-07-27 14:38 UTC
Hello there,

I just installed Nobara Linux 40 which comes with yumex. However, I'm not able to install any flatpaks using it.
There is always immediately an error message popup  about an User abort. The actual message is in german as my system is in german, but it appears immediately and is reproducible on the command line:

```
yumex --debug --flatpakref ~/Downloads/com.heroicgameslauncher.hgl.flatpakref 

(process:9212): Gtk-WARNING **: 16:17:50.317: Unknown key gtk-modules in /etc/xdg/gtk-4.0/settings.ini

(process:9212): Gtk-WARNING **: 16:17:50.317: Unknown key gtk-modules in /home/m1labbe/.config/gtk-4.0/settings.ini

(process:9212): Adwaita-WARNING **: 16:17:50.330: Using GtkSettings:gtk-application-prefer-dark-theme with libadwaita is unsupported. Please use AdwStyleManager:color-scheme instead.
16:17:50 DEBUG : (yumex) -  Version:  5.0.1 (DNF4)
16:17:50 DEBUG : (yumex) -  executable : /usr/bin/yumex
16:17:50 DEBUG : (yumex) -  commmand-line : Namespace(debug=True, exit=False, update=False, flatpakref='/home/m1labbe/Downloads/com.heroicgameslauncher.hgl.flatpakref')
16:17:50 DEBUG : (yumex) -  set_need_attetion (flatpak): state: False 
16:17:50 DEBUG : (yumex) -  window-height: 826
16:17:50 DEBUG : (yumex) -  window-width: 1000
16:17:50 DEBUG : (yumex) -  fullscreened: False
16:17:50 DEBUG : (yumex) -  maximized: False
16:17:50 DEBUG : (yumex) -  install flatpakref: /home/m1labbe/Downloads/com.heroicgameslauncher.hgl.flatpakref
16:17:50 DEBUG : (yumex) -  stack changed : flatpaks
16:17:50 DEBUG : (yumex) -  set_need_attetion (flatpak): state: False 
16:17:50 DEBUG : (yumex) -  install flatpakref: /home/m1labbe/Downloads/com.heroicgameslauncher.hgl.flatpakref
16:17:50 DEBUG : (yumex) -  >> Start do_transaction
16:17:50 DEBUG : (yumex) -  >> Running job : install_flatpakref.
16:17:50 DEBUG : (yumex) -  install flatpakref: /home/m1labbe/Downloads/com.heroicgameslauncher.hgl.flatpakref
16:17:50 DEBUG : (yumex) -   FlatpakTransaction: setup user transaction
16:17:50 DEBUG : (yumex) -   FlatpakTransaction: adding flatpakref /home/m1labbe/Downloads/com.heroicgameslauncher.hgl.flatpakref for install
16:17:50 DEBUG : (yumex) -   FlatpakTransaction: Running Transaction
16:17:51 DEBUG : (yumex) -  search changed : 
16:17:51 DEBUG : (yumex) -   FlatpakTransaction: ready
16:17:51 DEBUG : (yumex) -  Vom Benutzer abgebrochen
16:17:51 DEBUG : (yumex) -  show_message : Vom Benutzer abgebrochen
16:17:51 DEBUG : (yumex) -  << Completed job : install_flatpakref.
16:17:51 DEBUG : (yumex) -  set_need_attetion (flatpak): state: False 
16:17:51 DEBUG : (yumex) -  << End do_transaction
```

"Vom Benutzer abgebrochen" translates to "Aborted by user", but I did not do anything.

![grafik](https://github.com/user-attachments/assets/4b0533d7-de80-4194-bd41-b74f78d3729d)

What could be the cause of the issue?
Installing via `flatpak install` on the console works fine and the installed flatpaks appear in yumex.

Cheers,
Marcel

**Comment by timlau** [comment] 2024-07-29 11:45
duplicate of https://github.com/timlau/yumex-ng/issues/98

Fixed in the 5.0.2 release of yumex.

Sure that it will be available in Nobara 40 soon.

workaround is to run with an English locale.

**Closed by timlau** 2024-07-29 11:45 UTC
Labels: duplicate
